// 浮生 · 数据层（千禧年定制版）
// 出生年 2000。事件池按 3:1 pacing：前期精简(几乎全旁白)→中后期丰富(每节点有选择)
// 5 条贯穿一生的暗线用 flag 串联：
//   网吧线: early_internet(8岁) → game_addict(14岁) → gaokao_*(18岁) → tech_layoff(35岁)
//   父亲线: dad_smoking(5岁) → dad_health(40岁) → parent_passing(55岁) → lookback_dad(暮年)
//   情感线: first_crush(14岁) → college_love(20岁) → heartbroken(22岁) → married(30岁) → widowed(70岁)
//   房债线: mortgage(32岁) → laid_off_35(35岁) → mid_steady(45岁) → quiet_retire(58岁)
//   城市线: beidrift(24岁) → stay_big_city(30岁) → back_home(40岁前) → retire_choice(58岁)

export const STAGES = [
  { code:'S1', name:'婴幼',    ageRange:[0,3],  decisionRatio:0.08 },  // 几乎无选择
  { code:'S2', name:'学龄前',  ageRange:[4,6],  decisionRatio:0.18 },  // 1-2选择
  { code:'S3', name:'小学',    ageRange:[7,12], decisionRatio:0.30 },  // 3-4选择
  { code:'S4', name:'初中',    ageRange:[13,15],decisionRatio:0.55 },
  { code:'S5', name:'高中',    ageRange:[16,18],decisionRatio:0.72 },
  { code:'S6', name:'大学',    ageRange:[19,22],decisionRatio:0.68 },
  { code:'S7', name:'立业',    ageRange:[23,30],decisionRatio:0.62 },
  { code:'S8', name:'成家立业', ageRange:[31,45],decisionRatio:0.78 },
  { code:'S9', name:'收尾',    ageRange:[46,60],decisionRatio:0.45 },
  { code:'S10',name:'暮年',    ageRange:[61,75],decisionRatio:0.28 },
];

export const MAX_AGE_WEEKS = 75 * 52 + 4; // 3904

// ---------- 天赋 ----------
export const TALENTS = [
  { id:'zaoHui',   name:'早慧',     desc:'智力+2，但心境上限-1',           effects:{intel:+2,mood:-1}, caps:{mood:9} },
  { id:'linJia',   name:'邻家小孩', desc:'颜值+1，家境+1',                 effects:{charm:+1,family:+1} },
  { id:'tiRuo',    name:'体弱多病', desc:'体质-2，但疾病事件获得额外旁白', effects:{health:-2}, flag:'frail_child' },
  { id:'chengCun', name:'城中村',   desc:'家境-2，但 18 岁后家境每 5 年+1', effects:{family:-2}, flag:'shantytown' },
  { id:'zaoChan',  name:'早产儿',   desc:'体质上限锁 7，触发"奇迹康复"线索', effects:{health:0}, caps:{health:7}, flag:'preterm' },
  { id:'shuXiang', name:'书香门第', desc:'智力+1，家境+1，18 岁触发"是否继承家业"', effects:{intel:+1,family:+1}, flag:'scholar' },
  { id:'leGuan',   name:'天生的乐天', desc:'心境+2，负面事件概率略降',       effects:{mood:+2} },
  { id:'muNe',     name:'内向寡言', desc:'颜值-1，但心境更稳（上限+1）',     effects:{charm:-1}, caps:{mood:11} },
  { id:'jianRen',  name:'韧骨头',   desc:'体质+2，暮年健康衰减减半',         effects:{health:+2}, flag:'tough' },
  { id:'minGan',   name:'敏感',     desc:'智力+1，但心境-2，更易触发回忆',    effects:{intel:+1,mood:-2}, flag:'sensitive' },
];

// ---------- 千禧年时代背景事件 ----------
// triggerYear = 真实历史年份；出生年2000+年龄命中
export const ERA_EVENTS = [
  { id:'era_2001_911',  triggerYear:2001, narration:'电视里反复放两栋楼倒塌的画面。你才一岁，看不懂，只觉得妈妈抱你抱得很紧。' },
  { id:'era_2003_sars', triggerYear:2003, narration:'校门口有人卖板蓝根，卖空了。空气里都是消毒水的味道。幼儿园不让你出门。' },
  { id:'era_2008_olympic', triggerYear:2008, narration:'满大街都在说"北京欢迎你"。你举着小红旗在院子里跑了一下午。' },
  { id:'era_2008_quake',  triggerYear:2008, narration:'电视里一遍遍放地震的画面。妈妈偷偷抹眼泪，问你想捐多少零花钱。' },
  { id:'era_2010_expo',   triggerYear:2010, narration:'世博会的吉祥物叫海宝。同学书包上都挂一个。' },
  { id:'era_2011_weibo',  triggerYear:2011, narration:'家里通了微博。父亲第一次在上面骂了物业，被妈妈删了。' },
  { id:'era_2012_smartphone', triggerYear:2012, narration:'父亲换了智能机，开始低头划屏。餐桌上的话变少了。' },
  { id:'era_2013_double_reduction', triggerYear:2013, narration:'学校说"减负"。可作业反而多了，因为要"素质教育"。' },
  { id:'era_2015_stockcrash', triggerYear:2015, narration:'父亲下班回来脸色很差。饭桌上没人敢问股票。' },
  { id:'era_2017_shared_bike', triggerYear:2017, narration:'满街都是小黄车小红车。你骑去上学，车筐里能塞书包。' },
  { id:'era_2020_covid',  triggerYear:2020, narration:'你第一次戴上了口罩。街上空空荡荡，像被人按了静音。' },
  { id:'era_2022_lockdown',triggerYear:2022, narration:'宿舍又封了。泡面吃到最后，你闻见那味儿就想吐。' },
  { id:'era_2023_ai',     triggerYear:2023, narration:'所有人都在聊那个会写东西的AI。你用它写过一份作业，又删了。' },
];

// ---------- 事件池 ----------
// kind: 'mainBranch'(主分支强制) | 'threshold'(属性阈值) | 'stage'(年龄段) | 'relation'(关系)
export const EVENTS = [

  // ====================================================================
  // S1 婴幼 0-3 岁 · 几乎全旁白，0-2选择（前期精简策略）
  // 出生 2000 年正月，北方三线小城，国企末班车家庭
  // ====================================================================
  { id:'s1_birth', stage:'S1', ageRange:[0,0], kind:'mainBranch', weight:1000, once:true,
    narration:(s)=>`你出生在 2000 年正月的${s.attrs.family>=7?'省城':'北方三线小城'}。窗外下着雪，千禧年的钟声刚响过没几天。妈妈还没奶水，你哭了一整夜。`,
    choices:[] },
  { id:'s1_2m', stage:'S1', ageRange:[0,0], kind:'ambient', weight:8,
    narration:'爸爸请了三天假，第三天被叫回厂里。他亲了亲你的额头，胡茬扎得你脸疼。', choices:[] },
  { id:'s1_6m', stage:'S1', ageRange:[0,1], kind:'ambient', weight:6,
    narration:'墙上的钟滴答，妈妈抱着你来回走。窗外的雪化了一半。', choices:[] },
  { id:'s1_1y', stage:'S1', ageRange:[1,1], kind:'ambient', weight:6,
    narration:'你抓着妈妈的手指，攥得很紧。阳光照在摇篮边上，你第一次笑出了声。', choices:[] },
  { id:'s1_walk', stage:'S1', ageRange:[1,2], kind:'threshold', weight:18, once:true, requirement:{health:'>=4'},
    narration:'你扶着沙发沿走了几步，扑进妈妈怀里。屋里腾起一阵笑声。',
    choices:[{ text:'笑出声', effects:{mood:+1}, timeAdvanceWeeks:8 },{ text:'哭了', effects:{mood:-1}, timeAdvanceWeeks:8 }] },
  { id:'s1_quarrel', stage:'S1', ageRange:[2,3], kind:'threshold', weight:20, once:true, requirement:{mood:'<=6'},
    narration:'夜里听见摔碗声。你把被子拉过头顶，听见妈妈哭。',
    choices:[{ text:'闷头睡', effects:{mood:-1}, timeAdvanceWeeks:12, setFlags:['home_tense'] },
             { text:'爬起来看', effects:{mood:-2}, timeAdvanceWeeks:12, setFlags:['home_tense','witnessed_quarrel'] }] },
  { id:'s1_sars', stage:'S1', ageRange:[3,3], kind:'era', weight:5, once:true,
    narration:'幼儿园不让你去了。妈妈用84拖地，拖了三遍，气味呛人。', choices:[] },

  // ====================================================================
  // S2 学龄前 4-6 岁 · 1-2选择，定调原生家庭
  // ====================================================================
  { id:'s2_factory', stage:'S2', ageRange:[4,5], kind:'threshold', weight:30, once:true, requirement:{family:'<=5'},
    narration:'爸爸的厂子效益不好了。他开始整天坐在阳台抽烟，烟头攒了一罐子。',
    choices:[{ text:'拿走他的烟', effects:{mood:+1,family:+1}, timeAdvanceWeeks:24, narration:'爸爸愣了一下，把烟掐了。后来他再没在你面前抽过。', setFlags:['dad_quit_smoke'] },
             { text:'默默看他', effects:{mood:-1}, timeAdvanceWeeks:24, setFlags:['dad_smoking'] },
             { text:'出门找邻居小孩玩', effects:{charm:+1}, timeAdvanceWeeks:24, setFlags:['early_friend_circle'] }] },
  { id:'s2_kinder', stage:'S2', ageRange:[4,5], kind:'stage', weight:22, once:true,
    narration:'妈妈牵着你去幼儿园。你在门口死活不肯松手。',
    choices:[{ text:'哭着进去', effects:{mood:-1}, timeAdvanceWeeks:20 },
             { text:'被一个小孩拉走', effects:{charm:+1,mood:+1}, timeAdvanceWeeks:20, setFlags:['first_friend'] },
             { text:'死活不去', effects:{intel:+1,mood:0}, timeAdvanceWeeks:20, setFlags:['no_kinder'] }] },
  { id:'s2_lie', stage:'S2', ageRange:[5,6], kind:'stage', weight:20, once:true,
    narration:'你把碗摔碎了，跟妈妈说是猫干的。妈妈看了你半天。',
    choices:[{ text:'坚持是猫', effects:{mood:-1}, timeAdvanceWeeks:16, setFlags:['liar_early'] },
             { text:'承认', effects:{intel:+1,mood:+1}, timeAdvanceWeeks:16 }] },
  { id:'s2_olympic', stage:'S2', ageRange:[8,8], kind:'era', weight:5, once:true,
    narration:'北京奥运。你举着小红旗在院子里跑了一下午，手心全是汗。', choices:[] },

  // ====================================================================
  // S3 小学 7-12 岁 · 3-4选择，同伴世界打开，互联网初体验
  // ====================================================================
  { id:'s3_cafe', stage:'S3', ageRange:[8,10], kind:'stage', weight:28, once:true,
    narration:'街角开了网吧，两块钱一小时。同桌小明说带你去。',
    choices:[{ text:'去', effects:{intel:-1,mood:+2}, timeAdvanceWeeks:12, setFlags:['early_internet'] },
             { text:'不去', effects:{intel:+1}, timeAdvanceWeeks:12 },
             { text:'告诉老师', effects:{mood:-2,charm:-1}, timeAdvanceWeeks:12, setFlags:['tattle_tale'] }] },
  { id:'s3_class', stage:'S3', ageRange:[7,9], kind:'stage', weight:24, once:true, requirement:{family:'>=4'},
    narration:'妈妈问报不报兴趣班。墙上贴着书法、钢琴、奥数三张简章。',
    choices:[{ text:'书法', effects:{intel:+1,mood:0}, timeAdvanceWeeks:40, setFlags:['hobby_calli'] },
             { text:'钢琴', effects:{charm:+1,mood:-1}, timeAdvanceWeeks:40, setFlags:['hobby_piano'] },
             { text:'奥数', effects:{intel:+2,mood:-2}, timeAdvanceWeeks:40, setFlags:['hobby_math'] },
             { text:'什么都不报', effects:{mood:+2}, timeAdvanceWeeks:40, setFlags:['free_childhood'] }] },
  { id:'s3_bully', stage:'S3', ageRange:[9,11], kind:'threshold', weight:24, once:true, requirement:{charm:'<=4'},
    narration:'有人把你的书包扔进水沟。你站在那儿，没敢吱声。',
    choices:[{ text:'忍了', effects:{mood:-2}, timeAdvanceWeeks:8, setFlags:['bullied'] },
             { text:'推回去', effects:{charm:+1,mood:-1,health:-1}, timeAdvanceWeeks:8 },
             { text:'告诉父母', effects:{mood:0}, timeAdvanceWeeks:8, setFlags:['told_parents'] }] },
  { id:'s3_popular', stage:'S3', ageRange:[9,11], kind:'threshold', weight:24, once:true, requirement:{charm:'>=6'},
    narration:'课间操一圈人围着你。班长塞给你一颗糖。',
    choices:[{ text:'分给同学', effects:{charm:+1,mood:+1}, timeAdvanceWeeks:8 },
             { text:'自己吃', effects:{mood:+1}, timeAdvanceWeeks:8 }] },
  { id:'s3_smartphone', stage:'S3', ageRange:[12,12], kind:'era', weight:5, once:true,
    narration:'父亲换了智能机，开始低头划屏。餐桌上的话变少了。', choices:[] },
  { id:'s3_xiaoshengchu', stage:'S3', ageRange:[12,12], kind:'stage', weight:38, once:true,
    narration:'小升初。父母为择校吵了一架。',
    choices:[{ text:'去重点（托关系）', effects:{intel:+1,family:-1,mood:-1}, timeAdvanceWeeks:20, setFlags:['key_middle'], requirement:{family:'>=5'} },
             { text:'就近读普通校', effects:{mood:+1}, timeAdvanceWeeks:20 },
             { text:'回老家读', effects:{mood:-1}, timeAdvanceWeeks:20, setFlags:['left_behind'] }] },
  { id:'s3_reduced', stage:'S3', ageRange:[13,13], kind:'era', weight:5, once:true,
    narration:'学校说"减负"。可作业反而多了，因为要"素质教育"。', choices:[] },

  // ====================================================================
  // S4 初中 13-15 岁 · 每节点有选择，自我意识觉醒、初恋、叛逆
  // ====================================================================
  { id:'s4_crush', stage:'S4', ageRange:[14,15], kind:'threshold', weight:30, once:true, requirement:{charm:'>=5'},
    narration:'她在你前排，马尾一甩一甩。整节课你都在数她甩了几次。',
    choices:[{ text:'递纸条', effects:{mood:+2,charm:0}, timeAdvanceWeeks:12, setFlags:['first_crush'] },
             { text:'默默喜欢', effects:{mood:+1,intel:-1}, timeAdvanceWeeks:12 },
             { text:'假装不在意', effects:{mood:-1}, timeAdvanceWeeks:12 }] },
  { id:'s4_game', stage:'S4', ageRange:[13,15], kind:'threshold', weight:28, once:true, requirement:{intel:'<=6'},
    narration:'你在网吧通宵了一整夜。天亮出来，眼睛刺痛，早饭吃了两口就吐了。',
    choices:[{ text:'继续沉迷', effects:{intel:-2,health:-1,mood:+2}, timeAdvanceWeeks:30, setFlags:['game_addict'] },
             { text:'被父亲抓回家', effects:{mood:-2,intel:-1}, timeAdvanceWeeks:12, setFlags:['caught_gaming'] }] },
  { id:'s4_rebel', stage:'S4', ageRange:[14,15], kind:'stage', weight:22, once:true,
    narration:'母亲翻你的抽屉。你当着她的面把日记撕了。',
    choices:[{ text:'摔门出去', effects:{mood:-2}, timeAdvanceWeeks:8, setFlags:['rebel'] },
             { text:'坐下来谈', effects:{intel:+1,mood:-1}, timeAdvanceWeeks:8 }] },
  { id:'s4_track', stage:'S4', ageRange:[15,15], kind:'stage', weight:30, once:true,
    narration:'文理分科表发下来。你盯着"文科/理科"两个格看了很久。',
    choices:[{ text:'选理科', effects:{intel:+1}, timeAdvanceWeeks:20, setFlags:['track_science'] },
             { text:'选文科', effects:{intel:0,charm:+1}, timeAdvanceWeeks:20, setFlags:['track_arts'] }] },
  { id:'s4_phone', stage:'S4', ageRange:[14,15], kind:'stage', weight:20, once:true, requirement:{family:'>=4'},
    narration:'你想要一部自己的手机。父亲说"中考考好再说"。',
    choices:[{ text:'拼命学', effects:{intel:+2,health:-1}, timeAdvanceWeeks:20, setFlags:['own_phone'] },
             { text:'偷偷攒钱买', effects:{mood:-1,intel:-1}, timeAdvanceWeeks:20, setFlags:['own_phone'] }] },
  { id:'s4_body', stage:'S4', ageRange:[13,14], kind:'stage', weight:18, once:true,
    narration:'镜子里的脸变了样。长痘，声音卡在半路，你说话时总清嗓子，怕被同学听见。',
    choices:[{ text:'偷偷挤痘', effects:{charm:-1,health:-1}, timeAdvanceWeeks:12, setFlags:['picked_acne'] },
             { text:'学着不在乎', effects:{mood:+1}, timeAdvanceWeeks:12 },
             { text:'买瓶祛痘霜', effects:{family:-1,charm:+1}, timeAdvanceWeeks:12, setFlags:['bought_cream'] }] },
  { id:'s4_teacher', stage:'S4', ageRange:[14,15], kind:'stage', weight:18, once:true,
    narration:'语文老师把你作文圈出来，当堂念。念完说"你有点东西"。你脸烧了一整节课。',
    choices:[{ text:'回去接着写', effects:{intel:+1,mood:+1}, timeAdvanceWeeks:20, setFlags:['teacher_seen'] },
             { text:'不好意思再交', effects:{mood:-1}, timeAdvanceWeeks:20 },
             { text:'转去搞数学', effects:{intel:+1}, timeAdvanceWeeks:20, setFlags:['pivot_math'] }] },
  { id:'s4_smartphone_change', stage:'S4', ageRange:[15,15], kind:'stage', weight:18, once:true,
    narration:'班上建了QQ群。你第一次在群里发了张自拍，没人点赞，你删了。',
    choices:[{ text:'再发一次', effects:{charm:+1,mood:+1}, timeAdvanceWeeks:8 },
             { text:'不发了', effects:{mood:-1}, timeAdvanceWeeks:8 }] },
  { id:'s4_expo2010', stage:'S4', ageRange:[10,10], kind:'era', weight:5, once:true,
    narration:'世博会吉祥物海宝。同学书包上都挂一个，你没有。', choices:[] },

  // ====================================================================
  // S5 高中 16-18 岁 · 第一个高峰，高考主分支点
  // ====================================================================
  { id:'s5_pressure', stage:'S5', ageRange:[16,17], kind:'stage', weight:25, once:true,
    narration:'高三倒计时牌每天翻一页。同桌开始掉头发。你在本子边缘画了一只小恐龙。',
    choices:[{ text:'拼了命地学', effects:{intel:+2,health:-1,mood:-1}, timeAdvanceWeeks:40, setFlags:['grind'] },
             { text:'按部就班', effects:{intel:+1,mood:0}, timeAdvanceWeeks:40 },
             { text:'有点想放弃了', effects:{intel:-1,mood:-2}, timeAdvanceWeeks:40, setFlags:['senior_slump'] }] },
  { id:'s5_love_secret', stage:'S5', ageRange:[17,18], kind:'threshold', weight:22, once:true, requirement:{charm:'>=6'}, excludeIf:{flags:['first_crush']},
    narration:'TA把笔记推到你面前，说"借你"。扉页夹了张字条。',
    choices:[{ text:'在一起', effects:{mood:+3}, timeAdvanceWeeks:20, setFlags:['hs_love'] },
             { text:'装作没懂', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:8 }] },
  { id:'s5_boarding', stage:'S5', ageRange:[16,16], kind:'stage', weight:20, once:true,
    narration:'住校第一夜。室友打呼，你盯着天花板数羊，数到三百只睡着了。',
    choices:[{ text:'咬牙适应', effects:{health:+1,mood:0}, timeAdvanceWeeks:30 },
             { text:'偷偷哭', effects:{mood:-1}, timeAdvanceWeeks:30, setFlags:['homesick'] }] },
  { id:'s5_stockcrash', stage:'S5', ageRange:[15,15], kind:'era', weight:5, once:true,
    narration:'父亲下班回来脸色很差。饭桌上没人敢问股票。', choices:[] },
  // 主分支点 1：高考
  { id:'s5_gaokao', stage:'S5', ageRange:[18,18], kind:'mainBranch', weight:9999, once:true,
    narration:'六月蝉叫得人心烦。准考证攥出汗，监考老师走过你身边停了一下。',
    choices:[
      { text:'认真答完每一题', effects:{mood:-1}, timeAdvanceWeeks:2, setFlags:['gaokao_normal'], nextNode:'s5_result_normal' },
      { text:'最后一道大题赌一把', requirement:{intel:'>=6'}, effects:{mood:-2}, timeAdvanceWeeks:2, setFlags:['gaokao_gamble'], nextNode:'s5_result_gamble' },
      { text:'交白卷，回家', effects:{mood:+2,family:-2}, timeAdvanceWeeks:2, setFlags:['gaokao_dropout'], nextNode:'s5_result_dropout' },
    ] },
  { id:'s5_result_normal', stage:'S5', ageRange:[18,18], kind:'mainBranch', weight:0,
    narration:(s)=> s.attrs.intel>=7 ? '录取通知书来时是 211。父亲破天荒喝了酒，醉了说"咱家出大学生了"。' : '录取通知书来时是个普通二本。母亲把它压在玻璃板下，第二天就泛了黄边。',
    choices:[] },
  { id:'s5_result_gamble', stage:'S5', ageRange:[18,18], kind:'mainBranch', weight:0,
    narration:(s)=> s.attrs.intel>=8 ? '你赌对了。录取的是 985。后来很多年你都没再那么赌过。' : '赌输了。分数卡在一本线边上，最后去了个普通一本。',
    choices:[] },
  { id:'s5_result_dropout', stage:'S5', ageRange:[18,18], kind:'mainBranch', weight:0,
    narration:'你没再回学校。父亲半个月没跟你说话。',
    choices:[{ text:'南下打工', effects:{health:-1,mood:-1,family:-1}, timeAdvanceWeeks:40, setFlags:['south_migrant'] }] },

  // ====================================================================
  // S6 大学 19-22 岁 · 口罩三年重灾区，初恋分手
  // ====================================================================
  { id:'s6_major', stage:'S6', ageRange:[19,19], kind:'stage', weight:25, once:true, excludeIf:{flags:['gaokao_dropout']},
    narration:'报到那天，你站在专业介绍栏前。有人劝你转计算机。',
    choices:[{ text:'学计算机', effects:{intel:+2,mood:0}, timeAdvanceWeeks:40, setFlags:['cs_major'] },
             { text:'学金融', effects:{intel:+1,family:0}, timeAdvanceWeeks:40, setFlags:['fin_major'] },
             { text:'学中文', effects:{charm:+1,mood:+1}, timeAdvanceWeeks:40, setFlags:['lit_major'] }] },
  { id:'s6_club', stage:'S6', ageRange:[20,21], kind:'stage', weight:20, once:true, excludeIf:{flags:['gaokao_dropout']},
    narration:'社团招新摆了一条街。吉他社的学长冲你招手。',
    choices:[{ text:'加吉他社', effects:{charm:+2,mood:+1}, timeAdvanceWeeks:20, setFlags:['guitar'] },
             { text:'加辩论队', effects:{intel:+1,charm:+1}, timeAdvanceWeeks:20, setFlags:['debate'] },
             { text:'都不加', effects:{mood:0,intel:+1}, timeAdvanceWeeks:20 }] },
  { id:'s6_roommate', stage:'S6', ageRange:[19,20], kind:'stage', weight:18, once:true, excludeIf:{flags:['gaokao_dropout']},
    narration:'室友打游戏打到三点，键盘敲得像下雨。你翻来覆去，枕头捂耳朵捂到发烫。',
    choices:[{ text:'忍了', effects:{mood:-1,health:-1}, timeAdvanceWeeks:8, setFlags:['endured_roommate'] },
             { text:'当面说', effects:{charm:+1,mood:0}, timeAdvanceWeeks:8, setFlags:['spoke_up'] },
             { text:'买副降噪耳塞', effects:{family:-1,mood:+1}, timeAdvanceWeeks:8, setFlags:['earplugs'] }] },
  { id:'s6_first_money', stage:'S6', ageRange:[20,21], kind:'stage', weight:18, once:true, excludeIf:{flags:['gaokao_dropout','study_abroad']},
    narration:'家教第一次结钱，三百块，皱巴巴的。你在食堂点了份最贵的红烧肉。',
    choices:[{ text:'寄回家', effects:{family:+1,mood:+1}, timeAdvanceWeeks:12, setFlags:['sent_home'] },
             { text:'给自己买点东西', effects:{mood:+2,charm:+1}, timeAdvanceWeeks:12, setFlags:['first_treat'] },
             { text:'存着', effects:{family:+1}, timeAdvanceWeeks:12, setFlags:['saver'] }] },
  { id:'s6_love', stage:'S6', ageRange:[20,22], kind:'threshold', weight:25, once:true, requirement:{charm:'>=6'}, excludeIf:{flags:['gaokao_dropout']},
    narration:'图书馆的灯总是亮到很晚。TA把笔记推到你面前，说"借你"。',
    choices:[{ text:'在一起', effects:{mood:+3}, timeAdvanceWeeks:30, setFlags:['college_love'] },
             { text:'装作没懂', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:8 }] },
  { id:'s6_covid', stage:'S6', ageRange:[19,20], kind:'era', weight:5, once:true,
    narration:'你第一次戴上了口罩。宿舍封了，网课上了半年，闻见泡面味就反胃。', choices:[] },
  { id:'s6_lockdown', stage:'S6', ageRange:[22,22], kind:'era', weight:5, once:true,
    narration:'宿舍又封了。泡面吃到最后，你闻见那味儿就想吐。', choices:[] },
  { id:'s6_breakup', stage:'S6', ageRange:[22,22], kind:'threshold', weight:22, once:true, requirement:{flags:['college_love','hs_love','first_crush']},
    narration:'毕业季。你们在车站分了手，谁也没回头。雨下得很大。',
    choices:[{ text:'流泪上车', effects:{mood:-3}, timeAdvanceWeeks:12, setFlags:['heartbroken'] },
             { text:'祝 TA 好', effects:{mood:-1,charm:+1}, timeAdvanceWeeks:12 }] },
  { id:'s6_grad', stage:'S6', ageRange:[22,22], kind:'stage', weight:30, once:true, excludeIf:{flags:['gaokao_dropout']},
    narration:'毕业典礼那天风很大。校长说"前程似锦"，你只觉得茫然。行李堆了一地。',
    choices:[{ text:'考研', effects:{intel:+2,mood:-1}, timeAdvanceWeeks:52, setFlags:['grad_school'] },
             { text:'直接就业', effects:{family:0}, timeAdvanceWeeks:20, setFlags:['work_first'] },
             { text:'出国', requirement:{family:'>=7'}, effects:{intel:+2,family:-2}, timeAdvanceWeeks:52, setFlags:['study_abroad'] }] },
  { id:'s6_ai_year', stage:'S6', ageRange:[23,23], kind:'era', weight:5, once:true,
    narration:'所有人都在聊那个会写东西的AI。你用它写过一份简历，又删了重写。', choices:[] },

  // ====================================================================
  // S7 立业 23-30 岁 · 北漂、第一份工作、30岁主分支
  // ====================================================================
  { id:'s7_firstjob', stage:'S7', ageRange:[23,24], kind:'stage', weight:25, once:true, excludeIf:{flags:['gaokao_dropout','grad_school','study_abroad']},
    narration:'第一份工作的工牌是蓝色的。人事让你签名，你手有点抖。工位在角落，挨着饮水机。',
    choices:[{ text:'认真做事', effects:{intel:+1,mood:0}, timeAdvanceWeeks:40, setFlags:['diligent'] },
             { text:'摸鱼度日', effects:{mood:+1,intel:-1}, timeAdvanceWeeks:40, setFlags:['slacker'] }] },
  { id:'s7_rent', stage:'S7', ageRange:[24,26], kind:'stage', weight:22, once:true, excludeIf:{flags:['left_behind','south_migrant']},
    narration:'房租涨了三百。你在地铁里算了一遍又一遍，到公司时已经迟到。',
    choices:[{ text:'咬牙留下', effects:{mood:-1,family:-1}, timeAdvanceWeeks:40, setFlags:['beidrift'] },
             { text:'搬去合租', effects:{charm:+1,mood:0}, timeAdvanceWeeks:40 },
             { text:'回老家', effects:{mood:+1,family:+1}, timeAdvanceWeeks:40, setFlags:['back_home'] }] },
  { id:'s7_overtime', stage:'S7', ageRange:[25,28], kind:'stage', weight:20, once:true, excludeIf:{flags:['back_home']},
    narration:'又加班到凌晨。路灯把影子拉得很长，你数过，从公司到地铁站要走 1143 步。',
    choices:[{ text:'继续卷', effects:{intel:+1,health:-1,mood:-2}, timeAdvanceWeeks:30, setFlags:['burnout'] },
             { text:'摸鱼保命', effects:{mood:+1,intel:-1}, timeAdvanceWeeks:30 }] },
  // —— 立业期补强：师徒/相亲/份子钱/身体预警/升职饼，让 23-30 不再空转 ——
  { id:'s7_mentor', stage:'S7', ageRange:[23,25], kind:'stage', weight:22, once:true, excludeIf:{flags:['gaokao_dropout','grad_school','study_abroad']},
    narration:'带你的人姓周，发际线退到头顶。他递来一支烟，你摆手，他笑了笑，烟叼回嘴里。',
    choices:[{ text:'学着抽了一口', effects:{health:-1,charm:+1}, timeAdvanceWeeks:12, setFlags:['smoke_started'] },
             { text:'坚持不抽', effects:{mood:+1}, timeAdvanceWeeks:12, setFlags:['no_smoke'] },
             { text:'问他怎么熬上来的', effects:{intel:+1}, timeAdvanceWeeks:12, setFlags:['mentor_bond'] }] },
  { id:'s7_dating25', stage:'S7', ageRange:[25,27], kind:'stage', weight:24, once:true,
    narration:'妈妈电话里第三次提"那个谁家的孩子"。你挂了电话，外卖盒摞了三层没扔。',
    choices:[{ text:'答应去见见', effects:{mood:-1}, timeAdvanceWeeks:20, setFlags:['blind_date'] },
             { text:'说工作忙', effects:{mood:-2,intel:+1}, timeAdvanceWeeks:20 },
             { text:'谈了个对象', requirement:{charm:'>=5'}, effects:{mood:+2}, timeAdvanceWeeks:20, setFlags:['s7_love'] }] },
  { id:'s7_wedding_money', stage:'S7', ageRange:[26,29], kind:'stage', weight:20, once:true,
    narration:'高中同桌结婚了，请帖烫金字。你包了八百，装信封时手抖了一下。',
    choices:[{ text:'去，喝到醉', effects:{health:-1,mood:+1}, timeAdvanceWeeks:12 },
             { text:'托人带份子钱', effects:{mood:-1}, timeAdvanceWeeks:12, setFlags:['skip_wedding'] },
             { text:'去，提前离席', effects:{mood:-1,charm:+1}, timeAdvanceWeeks:12 }] },
  { id:'s7_body27', stage:'S7', ageRange:[27,29], kind:'threshold', weight:22, once:true, requirement:{health:'<=7'},
    narration:'体检单：颈椎曲度变直，轻度脂肪肝。医生说"年轻人少熬夜"。你点头，出门又点了杯冰美式。',
    choices:[{ text:'办了张健身卡', effects:{health:+1,family:-1}, timeAdvanceWeeks:16, setFlags:['gym_card'] },
             { text:'办了没去', effects:{mood:-1}, timeAdvanceWeeks:16, setFlags:['gym_unused'] },
             { text:'继续熬', effects:{health:-1}, timeAdvanceWeeks:16 }] },
  { id:'s7_promo_pie', stage:'S7', ageRange:[28,30], kind:'stage', weight:22, once:true, excludeIf:{flags:['back_home','civil_servant']},
    narration:'领导拍你肩："再扛扛，年底给你提。"你听出"年底"是哪年底。',
    choices:[{ text:'扛', effects:{health:-1,intel:+1,mood:-1}, timeAdvanceWeeks:24, setFlags:['promised_promo'] },
             { text:'开始看机会', effects:{mood:+1,intel:+1}, timeAdvanceWeeks:24, setFlags:['job_hopping'] },
             { text:'佛系', effects:{mood:0}, timeAdvanceWeeks:24 }] },
  { id:'s7_shared_bike', stage:'S7', ageRange:[17,17], kind:'era', weight:5, once:true,
    narration:'满街都是小黄车小红车。你骑去上班，车筐里塞公文包。', choices:[] },
  // 主分支点 2：三十而立
  { id:'s7_thirty', stage:'S7', ageRange:[30,30], kind:'mainBranch', weight:9999, once:true,
    narration:(s)=> `三十岁生日那天，没人记得。你对着蛋糕上的蜡烛发了会儿呆。${s.flags.includes('beidrift')?'窗外是北方冬天的雾霾，像一块灰布。':''}`,
    choices:[
      { text:'留在大城市', effects:{mood:-1,family:-1}, timeAdvanceWeeks:8, setFlags:['stay_big_city'] },
      { text:'回老家考公', effects:{mood:+1,family:+1}, timeAdvanceWeeks:8, setFlags:['civil_servant'] },
      { text:'出国闯闯', requirement:{intel:'>=6'}, effects:{family:-2,mood:0}, timeAdvanceWeeks:8, setFlags:['go_abroad'] },
      { text:'创业', requirement:{family:'>=6',intel:'>=7'}, effects:{family:-2,mood:-1}, timeAdvanceWeeks:8, setFlags:['startup'] },
    ] },

  // ====================================================================
  // S8 成家立业 31-45 岁 · 最丰富的高原期，双线压力(职场+家庭)
  // ====================================================================
  { id:'s8_marry', stage:'S8', ageRange:[28,32], kind:'threshold', weight:30, once:true, requirement:{charm:'>=5'},
    narration:'相亲第七个，你说就 TA 吧。领证那天，民政局人很多，没人看你们。',
    choices:[{ text:'办场婚礼', effects:{family:-2,mood:+2}, timeAdvanceWeeks:40, setFlags:['married'] },
             { text:'旅行结婚', effects:{mood:+1,family:0}, timeAdvanceWeeks:12, setFlags:['married'] }] },
  { id:'s8_wedding_day', stage:'S8', ageRange:[29,33], kind:'stage', weight:18, once:true, requirement:{flags:['married']},
    narration:'敬酒敬到第十八桌，胃里翻江倒海。司仪还在喊"百年好合"，你笑得脸僵了。',
    choices:[{ text:'硬撑到最后', effects:{health:-1,mood:-1,charm:+1}, timeAdvanceWeeks:4, setFlags:['big_wedding'] },
             { text:'中途躲洗手间缓', effects:{mood:0}, timeAdvanceWeeks:4 },
             { text:'拉着 TA 提前溜', effects:{mood:+2,charm:-1}, timeAdvanceWeeks:4, setFlags:['eloped_midway'] }] },
  { id:'s8_inlaw', stage:'S8', ageRange:[30,34], kind:'stage', weight:18, once:true, requirement:{flags:['married']},
    narration:'婆婆/岳母来住帮忙。厨房台面擦了三遍，她说你洗洁精放多了。你咬着筷子没吱声。',
    choices:[{ text:'忍', effects:{mood:-2}, timeAdvanceWeeks:24, setFlags:['inlaw_tension'] },
             { text:'跟对象抱怨', effects:{mood:-1,charm:-1}, timeAdvanceWeeks:24, setFlags:['spouse_caught_middle'] },
             { text:'搬出去单过', effects:{family:-1,mood:+1}, timeAdvanceWeeks:24, setFlags:['moved_out'] }] },
  { id:'s8_house', stage:'S8', ageRange:[30,35], kind:'stage', weight:25, once:true, excludeIf:{flags:['back_home','civil_servant','south_migrant','_none']},
    narration:'售楼处沙盘亮着灯。销售说"这户型就剩两套"。首付是两边父母凑的，存折翻得很旧。',
    choices:[{ text:'咬牙买', effects:{family:-3,mood:-1}, timeAdvanceWeeks:30, setFlags:['mortgage'] },
             { text:'再等等', effects:{mood:0}, timeAdvanceWeeks:30, setFlags:['no_house'] }] },
  { id:'s8_child', stage:'S8', ageRange:[30,34], kind:'threshold', weight:25, once:true, requirement:{}, excludeIf:{flags:['_none']},
    narration:'孩子出生那天，你在产房外坐了一夜。护士出来说"母女平安"，你才哭出来。',
    choices:[{ text:'好好养', effects:{family:-1,mood:+2}, timeAdvanceWeeks:40, setFlags:['had_child'] },
             { text:'交给老人带', effects:{mood:0,family:0}, timeAdvanceWeeks:40, setFlags:['had_child','grandparent_raise'] }] },
  { id:'s8_baby_year', stage:'S8', ageRange:[31,34], kind:'stage', weight:20, once:true, requirement:{flags:['had_child']},
    narration:'孩子夜醒第五次，奶粉冲好又凉了。你抱着娃在客厅转圈，窗外天蒙蒙亮。',
    choices:[{ text:'跟对象轮流熬', effects:{health:-1,mood:0}, timeAdvanceWeeks:24, setFlags:['shared_night'] },
             { text:'自己扛', effects:{health:-2,mood:-1}, timeAdvanceWeeks:24, setFlags:['solo_parent'] },
             { text:'请个月嫂', effects:{family:-1,mood:+1}, timeAdvanceWeeks:24, setFlags:['had_yuesao'] }] },
  { id:'s8_renovation', stage:'S8', ageRange:[31,34], kind:'stage', weight:16, once:true, requirement:{flags:['mortgage']},
    narration:'装修工人说这面墙是承重的，加三千改方案。你和对象在毛坯房里吵了一架，灰尘呛嗓子。',
    choices:[{ text:'加钱改', effects:{family:-1,mood:-1}, timeAdvanceWeeks:20, setFlags:['renov_done'] },
             { text:'将就', effects:{mood:-2}, timeAdvanceWeeks:20, setFlags:['renov_cheap'] },
             { text:'自己动手', effects:{health:-1,intel:+1}, timeAdvanceWeeks:20, setFlags:['diy_renov'] }] },
  { id:'s8_promo33', stage:'S8', ageRange:[33,36], kind:'stage', weight:20, once:true, excludeIf:{flags:['civil_servant','back_home']},
    narration:'升职名单下来了，没有你。比你来晚两年的小王在列。领导说"明年，明年一定"。',
    choices:[{ text:'当面问', effects:{charm:-1,intel:+1}, timeAdvanceWeeks:16, setFlags:['confronted_boss'] },
             { text:'默默更新简历', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:16, setFlags:['resume_out'] },
             { text:'认了', effects:{mood:-2}, timeAdvanceWeeks:16, setFlags:['swallowed_it'] }] },
  { id:'s8_dad_health', stage:'S8', ageRange:[40,42], kind:'threshold', weight:28, once:true, requirement:{}, excludeIf:{flags:['dad_quit_smoke']},
    narration:'父亲体检报告：肺结节。医生让随访。他在电话里说没事，你听出他喘。',
    choices:[{ text:'接来大城市看', effects:{family:-2,mood:-1}, timeAdvanceWeeks:20, setFlags:['dad_treated'] },
             { text:'托老家医院', effects:{mood:-2}, timeAdvanceWeeks:20, setFlags:['dad_untreated'] }] },
  { id:'s8_mortgage_pressure', stage:'S8', ageRange:[33,38], kind:'threshold', weight:24, once:true, requirement:{}, excludeIf:{flags:['no_house']},
    narration:'手机又弹了还款提醒。你按掉没看。账单、房贷、物业费，摞成一摞。',
    choices:[{ text:'接私活补窟窿', effects:{health:-1,intel:+1,mood:-1}, timeAdvanceWeeks:30, setFlags:['side_hustle'] },
             { text:'省着过', effects:{mood:-1,family:0}, timeAdvanceWeeks:30 }] },
  { id:'s8_child_school', stage:'S8', ageRange:[38,42], kind:'threshold', weight:22, once:true, requirement:{flags:['had_child']},
    narration:'孩子该上小学了。学区房的价格你看了三遍，每看一遍血压高一点。',
    choices:[{ text:'砸钱买学区房', effects:{family:-2,mood:-2}, timeAdvanceWeeks:30, setFlags:['school_district'] },
             { text:'就近读普通校', effects:{mood:0}, timeAdvanceWeeks:30 }] },
  // 主分支：35岁危机（呼应游戏_addict/early_internet线）
  { id:'s8_35crisis', stage:'S8', ageRange:[35,35], kind:'mainBranch', weight:9999, once:true, excludeIf:{flags:['civil_servant']},
    narration:(s)=> `HR 找你谈话时，你正在改一份 PPT。她说了三句，你只听清"交接"。${s.flags.includes('game_addict')?'你想起来，初中那年通宵打游戏也是这种眩晕。':''}`,
    choices:[
      { text:'拿赔偿走人', effects:{family:-1,mood:-2}, timeAdvanceWeeks:12, setFlags:['laid_off_35'] },
      { text:'降薪留下来', effects:{mood:-2,family:0}, timeAdvanceWeeks:12, setFlags:['paycut_35'] },
      { text:'自己单干', requirement:{intel:'>=6'}, effects:{family:-1,mood:-1}, timeAdvanceWeeks:12, setFlags:['solo_biz'] },
    ] },
  { id:'s8_ai_threat', stage:'S8', ageRange:[35,40], kind:'stage', weight:20, once:true, excludeIf:{flags:['civil_servant']},
    narration:'公司新来了个会用AI的应届生，效率是你三倍。领导看你的眼神变了。',
    choices:[{ text:'学AI转型', effects:{intel:+2,mood:-1}, timeAdvanceWeeks:30, setFlags:['ai_pivot'] },
             { text:'躺平等裁', effects:{mood:-2}, timeAdvanceWeeks:30 }] },
  { id:'s8_tempt', stage:'S8', ageRange:[36,41], kind:'stage', weight:16, once:true, requirement:{flags:['married']},
    narration:'同事给你带了杯咖啡，多加了一份糖。你接过来时指尖碰了一下，谁都没说话。',
    choices:[{ text:'把杯子推回去', effects:{mood:-1}, timeAdvanceWeeks:20, setFlags:['resisted_tempt'] },
             { text:'收下，没再多想', effects:{mood:+1}, timeAdvanceWeeks:20, setFlags:['coffee_moment'] },
             { text:'收下，心里动了一下', effects:{mood:+2,charm:+1}, timeAdvanceWeeks:20, setFlags:['heart_stirred'] }] },
  { id:'s8_teen_rebel', stage:'S8', ageRange:[40,44], kind:'stage', weight:18, once:true, requirement:{flags:['had_child']},
    narration:(s)=>`孩子摔了门，音乐开得震天响。${s.flags.includes('rebel')||s.flags.includes('game_addict')?'你想起自己当年也这样摔过门。':''}你站在门外，手举起来又放下。`,
    choices:[{ text:'砸门进去', effects:{mood:-2,charm:-1}, timeAdvanceWeeks:16, setFlags:['clashed_teen'] },
             { text:'在门外坐会儿', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:16, setFlags:['waited_out'] },
             { text:'留张字条', effects:{charm:+1}, timeAdvanceWeeks:16, setFlags:['left_note'] }] },
  { id:'s8_pregnancy_pressure', stage:'S8', ageRange:[34,38], kind:'stage', weight:18, once:true, excludeIf:{flags:['had_child','_none']},
    narration:'妻子说想再要一个。你算了一笔账，奶粉、学区房、课外班，没敢说话。',
    choices:[{ text:'要', effects:{family:-2,mood:+1}, timeAdvanceWeeks:40, setFlags:['had_second'] },
             { text:'不要', effects:{mood:-1}, timeAdvanceWeeks:8 }] },
  // 主分支点 3：中年抉择 45
  { id:'s8_fortyfive', stage:'S8', ageRange:[45,45], kind:'mainBranch', weight:9999, once:true,
    narration:(s)=>`四十五了。体检报告单上多了几个箭头。${s.flags.includes('had_child')?'孩子在青春期，关着门不理你，音乐开得震天响。':''}`,
    choices:[
      { text:'跳槽搏一把', effects:{mood:-1,family:-1}, timeAdvanceWeeks:8, setFlags:['mid_leap'] },
      { text:'守成度日', effects:{mood:0,family:0}, timeAdvanceWeeks:8, setFlags:['mid_steady'] },
      { text:'提前退休照顾父母', effects:{mood:+1,family:-1}, timeAdvanceWeeks:8, setFlags:['early_retire_care'] },
    ] },

  // ====================================================================
  // S9 收尾 46-60 岁 · 中年危机、健康、父母离世、子女高考
  // ====================================================================
  { id:'s9_physical', stage:'S9', ageRange:[48,52], kind:'stage', weight:25, once:true,
    narration:'体检报告：脂肪肝，血压偏高。医生让你少油少盐。你把烟藏到了抽屉最里层。',
    choices:[{ text:'开始跑步', requirement:{health:'>=4'}, effects:{health:+1,mood:+1}, timeAdvanceWeeks:40, setFlags:['morning_run'] },
             { text:'该吃吃该喝喝', effects:{health:-1,mood:+1}, timeAdvanceWeeks:40 }] },
  { id:'s9_climacteric', stage:'S9', ageRange:[46,50], kind:'stage', weight:18, once:true,
    narration:'夜里盗汗，心烦得睡不着。镜子里那张脸老了不止一岁。说不清是身体在变，还是心先累了。',
    choices:[{ text:'去医院查', effects:{health:0,mood:-1}, timeAdvanceWeeks:16, setFlags:['checked_climacteric'] },
             { text:'忍着', effects:{mood:-2,health:-1}, timeAdvanceWeeks:16 },
             { text:'去跳广场舞', effects:{mood:+1,health:+1,charm:+1}, timeAdvanceWeeks:16, setFlags:['square_dance'] }] },
  { id:'s9_reunion', stage:'S9', ageRange:[48,52], kind:'stage', weight:20, once:true,
    narration:(s)=>`高中三十年聚会。包厢里有人开奔驰，有人骑电瓶车来的。${s.flags.includes('beidrift')||s.flags.includes('stay_big_city')?'你从大城市赶回，夹在中间。':'你坐在中间，谁也不偏。'}`,
    choices:[{ text:'多敬几杯', effects:{health:-1,charm:+1}, timeAdvanceWeeks:8 },
             { text:'坐角落听', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:8 },
             { text:'提前散了', effects:{mood:0}, timeAdvanceWeeks:8, setFlags:['left_reunion'] }] },
  { id:'s9_sibling', stage:'S9', ageRange:[55,58], kind:'stage', weight:20, once:true, requirement:{flags:['dad_gone']},
    narration:'母亲的养老摆在饭桌上。兄弟姐妹你一言我一语，最后都看你。',
    choices:[{ text:'接母亲来', effects:{family:-1,mood:+1}, timeAdvanceWeeks:24, setFlags:['mother_with_us'] },
             { text:'凑钱请人', effects:{family:-1,mood:-1}, timeAdvanceWeeks:24, setFlags:['hired_help'] },
             { text:'轮流伺候', effects:{mood:-1}, timeAdvanceWeeks:24, setFlags:['shared_care'] }] },
  { id:'s9_fraud', stage:'S9', ageRange:[54,58], kind:'stage', weight:16, once:true,
    narration:'理财群里有人发"稳赚15%"的项目，截图都是收益。你盯着看了半天，手指悬在转账键上。',
    choices:[{ text:'投', effects:{family:-2}, timeAdvanceWeeks:12, setFlags:['scammed'] },
             { text:'问孩子', effects:{mood:0,intel:+1}, timeAdvanceWeeks:12, setFlags:['asked_child'] },
             { text:'退群', effects:{mood:+1}, timeAdvanceWeeks:12, setFlags:['quit_invest_group'] }] },
  { id:'s9_childgaokao', stage:'S9', ageRange:[48,52], kind:'threshold', weight:25, once:true, requirement:{flags:['had_child']},
    narration:'孩子高考那天，你在考场外站了一上午。太阳很毒，你想起自己十八岁那年蝉叫得人心烦。',
    choices:[{ text:'默默等', effects:{mood:-1}, timeAdvanceWeeks:8, setFlags:['child_gaokao'] },
             { text:'回家做饭', effects:{mood:0}, timeAdvanceWeeks:8, setFlags:['child_gaokao'] }] },
  { id:'s9_parent_passing', stage:'S9', ageRange:[55,58], kind:'mainBranch', weight:9999, once:true,
    narration:(s)=> s.flags.includes('dad_smoking')||s.flags.includes('dad_untreated')
      ? '父亲住院了。肺。走廊的灯白得刺眼，你守了三夜。最后一夜他没醒过来。'
      : '父亲住院了。心脏。走廊的灯白得刺眼，你守了三夜。',
    choices:[{ text:'陪到最后一刻', effects:{mood:-3,family:+1}, timeAdvanceWeeks:20, setFlags:['parent_passing','dad_gone'] },
             { text:'请护工，自己上班', effects:{mood:-2,family:-1}, timeAdvanceWeeks:20, setFlags:['parent_passing','dad_gone'] }] },
  { id:'s9_mother_alone', stage:'S9', ageRange:[57,59], kind:'stage', weight:22, once:true, requirement:{flags:['dad_gone']},
    narration:'母亲一个人住在老房子。你打电话，她说"没事没事"，挂得很快。',
    choices:[{ text:'接来同住', effects:{family:-1,mood:+1}, timeAdvanceWeeks:30, setFlags:['mother_with_us'] },
             { text:'请钟点工', effects:{family:0,mood:-1}, timeAdvanceWeeks:30 },
             { text:'每周回去一次', effects:{mood:0}, timeAdvanceWeeks:30, setFlags:['weekly_visit'] }] },
  { id:'s9_retire', stage:'S9', ageRange:[58,60], kind:'stage', weight:30, once:true,
    narration:'退休证是个小红本。领导说了句"辛苦了"，你拎着纸箱走出呆了二十年的楼。电梯里没人说话。',
    choices:[{ text:'养花钓鱼', effects:{mood:+2}, timeAdvanceWeeks:40, setFlags:['quiet_retire'] },
             { text:'带孙子', effects:{mood:+1,family:+1}, timeAdvanceWeeks:40, setFlags:['raise_grandchild'] },
             { text:'报老年大学', effects:{intel:+1,mood:+1}, timeAdvanceWeeks:40, setFlags:['senior_college'] }] },
  { id:'s9_empty_nest', stage:'S9', ageRange:[55,58], kind:'stage', weight:20, once:true, requirement:{flags:['had_child']},
    narration:'孩子去外地念大学了。屋子突然空了，你们两口子吃饭都不太说话。',
    choices:[{ text:'找点事做', effects:{mood:+1,intel:+1}, timeAdvanceWeeks:30 },
             { text:'适应着过', effects:{mood:-1}, timeAdvanceWeeks:30, setFlags:['empty_nest'] }] },

  // ====================================================================
  // S10 暮年 61-75 岁 · 回望机制读 flags，第一人称回忆口吻
  // ====================================================================
  { id:'s10_lookback_intro', stage:'S10', ageRange:[63,65], kind:'mainBranch', weight:9999, once:true,
    narration:(s)=> {
      const lines = [];
      // 网吧线回引
      if (s.flags.includes('early_internet')||s.flags.includes('game_addict')) lines.push('你还记得街角那家网吧，两块钱一小时。后来你在它原来的位置吃了顿饭馆，门口贴着"招租"。');
      // 高考线回引
      else if (s.flags.includes('gaokao_gamble')) lines.push('你还记得十八岁那年赌了一把，把最后一道大题写满了。后来很多年，你都没再那么赌过。');
      else if (s.flags.includes('gaokao_normal')) lines.push('你还记得十八岁那个下午，窗外知了叫得厉害。你一道一道答完，没敢回头。');
      else if (s.flags.includes('gaokao_dropout')) lines.push('你还记得没去考的那年。卷子发下来那天，你在南下火车上睡了一路。');
      // 父亲线回引
      if (s.flags.includes('dad_gone')) lines.push('父亲走得那天，走廊的灯白得刺眼。你想起他阳台上的烟头攒了一罐子。');
      // 情感线回引
      if (s.flags.includes('heartbroken')) lines.push('想起车站那次分手。后来你也再没那样喜欢过谁。');
      if (s.flags.includes('college_love')) lines.push('想起图书馆那盏亮到很晚的灯。TA 的笔记还在你箱底。');
      if (!lines.length) lines.push('你想起很多个下午，阳光斜斜地照进来。好像什么都发生了，又好像什么都没。');
      return lines.join(' ');
    }, choices:[] },
  { id:'s10_old_ill', stage:'S10', ageRange:[68,72], kind:'threshold', weight:25, once:true, requirement:{health:'<=4'},
    narration:'腿脚越来越沉。上三楼要歇两歇，膝盖像生了锈。',
    choices:[{ text:'坚持遛弯', effects:{health:0,mood:+1}, timeAdvanceWeeks:20 },
             { text:'坐轮椅让人推', effects:{mood:-1}, timeAdvanceWeeks:20, setFlags:['wheelchair'] }] },
  { id:'s10_old_friend', stage:'S10', ageRange:[68,72], kind:'stage', weight:18, once:true,
    narration:'老伙计走了。葬礼上没几个人，你站最后一排，没掉眼泪，回家才觉得屋里空了一块。',
    choices:[{ text:'翻出老照片看了半宿', effects:{mood:-1,intel:+1}, timeAdvanceWeeks:8, setFlags:['mourned_friend'] },
             { text:'把他的号码存着没删', effects:{mood:-2}, timeAdvanceWeeks:8 },
             { text:'去公园他常坐的凳子上坐会儿', effects:{mood:0}, timeAdvanceWeeks:8 }] },
  { id:'s10_spouse', stage:'S10', ageRange:[70,74], kind:'stage', weight:25, once:true,
    narration:'老伴走得那天，窗台上的君子兰开了第三茬。你没哭，把花搬进屋。',
    choices:[{ text:'把花搬进屋', effects:{mood:+1}, timeAdvanceWeeks:12, setFlags:['widowed'] },
             { text:'坐在阳台一整天', effects:{mood:-2}, timeAdvanceWeeks:12, setFlags:['widowed'] }] },
  { id:'s10_live_alone', stage:'S10', ageRange:[72,75], kind:'stage', weight:20, once:true, requirement:{flags:['widowed']},
    narration:'一个人吃饭，做多了剩三天。电视开着不是为看，是为听见个人声。',
    choices:[{ text:'去养老院', effects:{family:-1,mood:0}, timeAdvanceWeeks:20, setFlags:['nursing_home'] },
             { text:'让孩子接', effects:{family:-1,mood:+1}, timeAdvanceWeeks:20, setFlags:['moved_to_child'] },
             { text:'自己撑着', effects:{mood:-1,health:-1}, timeAdvanceWeeks:20, setFlags:['stubborn_alone'] }] },
  { id:'s10_grandchild', stage:'S10', ageRange:[70,74], kind:'stage', weight:18, once:true, requirement:{flags:['had_child']},
    narration:'孙子扑过来喊你，口水蹭你一脸。你举着他转圈，膝盖咯吱响也没松手。',
    choices:[{ text:'多带带', effects:{mood:+2,family:+1}, timeAdvanceWeeks:16, setFlags:['raise_grandchild'] },
             { text:'怕闪了腰，少带', effects:{mood:0}, timeAdvanceWeeks:16 }] },
  { id:'s10_child_visit', stage:'S10', ageRange:[68,72], kind:'stage', weight:22, once:true, requirement:{flags:['had_child']},
    narration:'孩子打电话说周末回来。你提前三天就开始买菜单，到周六又说"别折腾了"。',
    choices:[{ text:'坚持让孩子回来', effects:{mood:+1,family:+1}, timeAdvanceWeeks:12 },
             { text:'说别来了', effects:{mood:-1}, timeAdvanceWeeks:12, setFlags:['let_go'] }] },
  { id:'s10_memory', stage:'S10', ageRange:[73,75], kind:'stage', weight:20, once:true,
    narration:'老花镜找不到了，你摸索了半天。阳光晒得人发困，你想起了很远的事，又想不起是哪件。',
    choices:[{ text:'不找了，睡一会儿', effects:{mood:+1}, timeAdvanceWeeks:12 },
             { text:'继续找', effects:{mood:-1}, timeAdvanceWeeks:12 }] },
];

// ---------- 兜底旁白池（按阶段，感官化白描，每段8-10条不重复） ----------
export const AMBIENT = {
  S1:[
    '墙上的钟滴答，妈妈抱着你来回走。窗外的雪化了一半。',
    '你抓着妈妈的手指，攥得很紧，指甲掐进肉里她也不松。',
    '窗外有麻雀叫。阳光照在摇篮边上，灰尘在光里浮。',
    '电视里在放新闻，爸爸盯着看了很久，没说话，烟灰掉了一截。',
    '你学会翻身了，在床上翻来覆去像条小鱼，妈妈笑出了声。',
    '邻居家姐姐来抱你，你闻到她身上香香的粉味，打了个喷嚏。',
    '下雨了。屋檐的水滴成一条线，你盯着看了很久，眼皮打架。',
    '爸爸的呼噜声穿过墙。你醒了，妈妈轻轻拍你，又睡了。',
    '收音机里在唱老歌，妈妈跟着哼，你听见她的声音就安静了。',
    '你长牙了，咬什么都咬，咬妈妈手指咬得她直抽气。',
    '阳台上的君子兰开了。奶奶说这花有灵性，你听不懂。',
    '夜里停电，妈妈点蜡烛。火苗晃，你的影子在墙上晃。',
  ],
  S2:[
    '你在院子里追一只黄猫，追了一下午，摔了三跤。',
    '电视里在放动画，你看了半集就睡着了，口水流到枕头上。',
    '妈妈教你说"妈妈"，你说了半天，最后蹦出一个"爸"。',
    '邻居家小孩来串门，你们为了一块糖打了一架，又和好。',
    '幼儿园午睡，你盯着天花板上的水渍发呆，像只兔子。',
    '爸爸下班回来，烟味和汗味混在一起，你躲开了。',
    '你把饭碗扣在头上，妈妈追着擦，你咯咯笑。',
    '电视里广告放了一遍又一遍，你跟着背了下来。',
    '下雨天不能出门，你在屋里转圈，转到头晕。',
    '奶奶给你缝了个布老虎，你抱着睡了半年，耳朵先磨破。',
    '邻居家买了一台VCD，你趴在窗户上看了一下午动画片。',
    '你第一次吃冰棍，咬太快冰了牙，哇地哭了。',
  ],
  S3:[
    '放学路上，你踩着地上的影子走，踩一个少一个。',
    '蝉叫了一整天，作业本被风吹翻了好几页，你懒得压。',
    '同桌借了你半块橡皮，你一直没还，后来就忘了。',
    '校门口卖辣条的大爷推着车走了，你追了两步没追上。',
    '你在作文本上写"我的理想"，写了三行划掉两行。',
    '班里图书角，你翻了本《十万个为什么》，翻到恐龙页就停了。',
    '课间操排队，你盯着前面同学的后脑勺数头发。',
    '回家路上买了个烤红薯，捂在手心，舍不得吃。',
    '你在课桌上刻了道线，同桌越线你就瞪他。',
    '数学考砸了，你把卷子折成纸飞机，飞到讲台上。',
    '班里的女孩开始传纸条，你没收到，假装不在意。',
    '放学下大雨，你没伞，冲回家淋成落汤鸡，却笑了。',
  ],
  S4:[
    '晚自习的灯管嗡嗡响。你盯着窗外发呆，被老师敲了桌子。',
    '你在本子边缘画了一只小恐龙，画了一整页。',
    '走廊里有男生在弹吉他，断断续续的，你听了一节课。',
    '食堂的饭很难吃，你还是吃了三年，最后竟有点怀念。',
    '你说了一句脏话，被自己吓了一跳。',
    '课本扉页被你写满了名字，又涂黑了。',
  ],
  S5:[
    '试卷摞起来比字典还厚。墨水的味道你闻了一整年。',
    '食堂的饭很难吃，你还是吃了三年。',
    '宿舍熄灯后，你打着手电看小说，电池用完才睡。',
    '走廊的灯坏了一盏，闪了半个月没人修。',
    '你站在操场看夕阳，看了很久，直到铃响。',
    '倒计时牌翻到 30 天，同桌开始掉头发，你也开始掉。',
  ],
  S6:[
    '宿舍的灯十一点准时熄。你打着手电看小说，电池用完才睡。',
    '操场上有人在弹吉他，断断续续的，你听了半天。',
    '图书馆的空调开得很足，你穿少了，打了一下午喷嚏。',
    '食堂的麻辣烫排了半小时队，到你时刚好卖完。',
    '你在朋友圈发了张图书馆的照片，配文"奋斗"，三秒后删了。',
    '舍友打游戏打到凌晨，你戴着耳塞还是能听见。',
  ],
  S7:[
    '地铁里的人都不说话。你也学会了不说话。',
    '加班到凌晨，路灯把影子拉得很长，你数过是 1143 步。',
    '合租的室友又没洗碗，水池里摞了一摞。',
    '外卖小哥敲门时你正在开会，饭凉了才吃。',
    '周末睡到中午，窗帘没拉开，屋里黑得像傍晚。',
    '你在便利店买了罐啤酒，站在街角喝完，没醉。',
  ],
  S8:[
    '孩子的作业本摊了一桌。你辅导到第九遍时，声音提高了。',
    '账单、房贷、物业费，摞成一摞。你按顺序付，付完一身汗。',
    '加班到半夜回家，孩子已经睡了，妻子在沙发上也睡了。',
    '父亲打电话来，问了句"忙不忙"，你说"还行"，挂了。',
    '体检报告你看了三遍，每个箭头都查了百度，越查越慌。',
    '周末想歇着，又被叫去陪客户喝酒，喝到吐。',
  ],
  S9:[
    '体检报告单你看了三遍，每个箭头都查了百度。',
    '同事的退休欢送会上，你说了句"保重"，没再说别的。',
    '孩子打电话来，问你身体，你说"好着呢"，挂得很快。',
    '早晨醒来，关节咔咔响，像生了锈的门。',
    '你在阳台浇花，浇了半天才发现是假花。',
    '老伴在厨房炖汤，香味飘了一屋子，你坐着没动。',
  ],
  S10:[
    '电视开着，你没看。窗台上的君子兰开了第三茬。',
    '老花镜找不到了，你摸索了半天。',
    '阳光晒得人发困。你想起了很远的事，又想不起是哪件。',
    '邻居家的孙子来敲门卖糖，你买了三颗，一颗都没吃。',
    '你坐在阳台看了一下午的天。屋子很静，静得能听见钟走。',
    '收音机里在放老歌，你跟着哼了两句，词忘了。',
    '孙子发来视频，你盯着看了三遍，没听清说什么。',
  ],
};

// ---------- 结局 ----------
export const GRADES = [
  { id:'g1', name:'潦草', min:0,  desc:'一生仓促，许多事来不及。' },
  { id:'g2', name:'寻常', min:18, desc:'平平稳稳，没什么大事。' },
  { id:'g3', name:'安稳', min:26, desc:'有苦有甜，终归有个着落。' },
  { id:'g4', name:'体面', min:34, desc:'该有的都有，体面收场。' },
  { id:'g5', name:'丰盈', min:42, desc:'一生饱满，少有遗憾。' },
  { id:'g6', name:'未尽', min:50, desc:'纵有万千，仍有未尽之愿。' },
];

// 叙事结局模板：condition 命中即用，按顺序匹配第一个（覆盖千禧一代各路径）
export const ENDING_TEMPLATES = [
  { id:'e_warm', condition:(s)=>s.moodAvg>=6.5,
    text:(s)=>`你这辈子没挣下什么大钱，但 ${s.flags.includes('had_child')?'孩子逢年过节都回':'也总算有枝可依'}。临了那天阳光很好，你睡过去了。算得上温暖平凡的一生。` },
  { id:'e_lonely', condition:(s)=>s.flags.includes('widowed') && s.moodAvg<5,
    text:()=>'你坐在阳台看了一下午的天。屋子里很静，静得能听见钟走。最后谁也没在身边。算孤独终老。' },
  { id:'e_steady', condition:(s)=>s.flags.includes('civil_servant')||s.flags.includes('mid_steady'),
    text:()=>'体制内熬到退休，工资不高，胜在稳。你常说"比上不足比下有余"。一辈子就这么过去了，体面。' },
  { id:'e_drift', condition:(s)=>s.flags.includes('beidrift')||s.flags.includes('stay_big_city'),
    text:(s)=>`北漂半生，${s.flags.includes('mortgage')?'房贷还清那年你大病一场':'最后也没扎下根'}。你说不清是赢了还是输了。或许都算不上。` },
  { id:'e_unfinished', condition:(s)=>s.flags.includes('startup')||s.flags.includes('mid_leap')||s.flags.includes('solo_biz'),
    text:()=>'折腾了大半辈子，公司黄过又开过。账上的钱来来去去。你常想，要是当年稳一点会怎样。未尽之愿。' },
  { id:'e_tech_layoff', condition:(s)=>s.flags.includes('laid_off_35')||s.flags.includes('ai_pivot'),
    text:(s)=>`35岁那年HR找你谈话，你只听清"交接"两个字。${s.flags.includes('ai_pivot')?'后来你学了AI，又干了十年。':'后来你换了几份工，越换越次。'}想起十八岁那年的蝉叫，还像昨天。` },
  { id:'e_abroad', condition:(s)=>s.flags.includes('study_abroad')||s.flags.includes('go_abroad'),
    text:()=>'你在国外待了半辈子，绿卡有了，根却没扎下。临了想回老家，老房子早没了。算漂泊一生。' },
  { id:'e_quiet', condition:(s)=>s.flags.includes('quiet_retire')||s.flags.includes('back_home'),
    text:()=>'回了老家，种种花钓钓鱼。日子慢得像水。你说这就够了。安稳一生。' },
  { id:'e_plain', condition:()=>true,
    text:()=>'没什么大起大落，也没什么特别值得讲的故事。寻常人寻常一生，也就这样了。' },
];
